#!/usr/bin/env python3
"""Verify tree evidence, integer sufficient statistics, and fresh deterministic replay.

Without raw archives, --aggregate-only verifies all primary intervals from the
tracked integer statistics. Raw archives are generated by run_trees.py and are
included in the full research supplement. It never presents aggregate checks as
independent replication of the experiment.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import math
import subprocess
import sys
import tempfile
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.analyze_trees import empirical_bernstein


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sufficient(raw, config, denominator: int) -> dict:
    ci = list(raw['cs']).index(config['primary_C'])
    bi = list(raw['bs']).index(config['primary_B'])
    v = raw['scores'][:, :, :, ci, bi].astype(np.int64)
    mapping = {'dividend': (0, 1), 'recursive': (0, 3),
               'fixed_author': (1, 3), 'random_search': (2, 3)}
    families = {}
    for fi, name in enumerate(config['families']):
        contrasts = {}
        for key, (left, right) in mapping.items():
            z = v[fi, :, left] - v[fi, :, right]
            contrasts[key] = {'sum_integer': int(z.sum()),
                              'sum_squared_integer': int((z*z).sum())}
        families[name] = {'method_score_sums': v[fi].sum(axis=0).tolist(),
                          'contrasts': contrasts}
    return {'n_per_family': int(v.shape[1]), 'denominator': denominator,
            'method_order': ['recursive', 'fixed_author', 'random_search', 'seed'],
            'families': families}


def interval_from_sufficient(row: dict, n: int, denominator: int, j: int,
                             delta: float = .05) -> tuple[float, float, float]:
    total = row['sum_integer']; squares = row['sum_squared_integer']
    mean = total / (n * denominator)
    variance = (squares - total*total/n) / ((n-1)*denominator**2)
    if variance < -1e-12:
        raise ValueError('Inconsistent integer sufficient statistics')
    log = math.log(4*j/delta)
    radius = math.sqrt(2*max(0., variance)*log/n) + 14*log/(3*(n-1))
    return mean, max(-1., mean-radius), min(1., mean+radius)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--aggregate-only', action='store_true')
    parser.add_argument('--write-sufficient', action='store_true')
    args = parser.parse_args()
    checks = []
    for dirname, protocol_name in [('trees', 'protocol_trees.json'),
                                    ('trees_confirmation', 'protocol_trees_confirmation.json')]:
        out = ROOT / 'results' / dirname
        meta = json.loads((out/'metadata.json').read_text())
        cfg = meta['executed_config']
        assert sha(ROOT/protocol_name) == meta['protocol_sha256']
        summary = json.loads((out/'summary.json').read_text())
        if args.write_sufficient:
            with np.load(out/'raw.npz', allow_pickle=False) as raw:
                st = sufficient(raw, cfg, meta['score_denominator'])
            (out/'sufficient.json').write_text(json.dumps(st, indent=2)+'\n')
        st = json.loads((out/'sufficient.json').read_text())
        n, denom = st['n_per_family'], st['denominator']
        assert n == cfg['development_runs_per_family']
        for row in summary['primary']:
            key = row['family']
            computed = interval_from_sufficient(st['families'][key]['contrasts']['dividend'],
                                               n, denom, cfg['primary_contrasts'])
            np.testing.assert_allclose(computed, [row[k] for k in ['mean','lower','upper']], atol=1e-14)
            np.testing.assert_allclose(np.asarray(st['families'][key]['method_score_sums'])/(n*denom),
                                       [row[k] for k in ['mean_R','mean_F','mean_random','mean_seed']], atol=1e-14)
        for row in summary['seed_gains']:
            computed = interval_from_sufficient(st['families'][row['family']]['contrasts'][row['regime']],
                                               n, denom, cfg['seed_gain_contrasts'])
            np.testing.assert_allclose(computed, [row[k] for k in ['mean','lower','upper']], atol=1e-14)
        checks.append(f'{dirname}: protocol hash, all 12 finite-sample intervals, and all method means verified from integer statistics')
        if args.aggregate_only:
            continue
        assert sha(out/'raw.npz') == meta['raw_sha256']
        assert sha(out/'primary.csv') == meta['primary_sha256']
        for source, digest in meta['source_sha256'].items():
            canonical = ROOT/source
            archived = out/'executed_sources'/Path(source).name
            matches_current = canonical.exists() and sha(canonical) == digest
            matches_archived = archived.exists() and sha(archived) == digest
            assert matches_current or matches_archived, source
        with np.load(out/'raw.npz', allow_pickle=False) as raw:
            assert sufficient(raw, cfg, denom) == st
            with tempfile.TemporaryDirectory() as tmp:
                subprocess.run([sys.executable, str(ROOT/'scripts/run_trees.py'),
                                '--protocol', str(ROOT/protocol_name), '--runs', '2',
                                '--output', tmp], check=True, capture_output=True)
                with np.load(Path(tmp)/'raw.npz', allow_pickle=False) as replay:
                    for name in ['scores','train','policies','accepted','diagnostics']:
                        np.testing.assert_array_equal(raw[name][:, :2], replay[name])
        checks.append(f'{dirname}: source/raw/CSV hashes and first two seeds of every family replay bitwise')
    report = {'status': 'PASS', 'aggregate_only': args.aggregate_only, 'checks': checks,
              'note': 'Numerical/source checks are not novelty certification or independent human proof review.'}
    path = ROOT/'results'/('trees_aggregate_verification.json' if args.aggregate_only else 'trees_verification.json')
    path.write_text(json.dumps(report, indent=2)+'\n')
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    main()
